In [1]:
import os
import numpy as np
import pandas as ps
import matplotlib.pyplot as plt
# from SequenceAlignments import Needleman_and_wunsch as nw
from Sequence_Alignments import Needleman_and_wunsch

# Needleman & Wunsch Algorithm

In [2]:
# initialize
letters =['A','C','G','T']
match_score = 1
mismatch_soce = -2
gap = -1
nw_nucleotides = Needleman_and_wunsch(letters,match_score,mismatch_soce,gap)
distance_matrix = nw_nucleotides.distance()
print(distance_matrix)

{'A': {'A': 1.0, 'C': -2.0, 'G': -2.0, 'T': -2.0}, 'C': {'A': -2.0, 'C': 1.0, 'G': -2.0, 'T': -2.0}, 'G': {'A': -2.0, 'C': -2.0, 'G': 1.0, 'T': -2.0}, 'T': {'A': -2.0, 'C': -2.0, 'G': -2.0, 'T': 1.0}}


In [3]:
A = ['C','A','T','G','A','C']
B = ['T','C','T','G','A','A','C']
score_matrix = nw_nucleotides.score_matrix(A,B)
print(score_matrix)

[[ 0. -1. -2. -3. -4. -5. -6.]
 [-1. -2. -3. -1. -2. -3. -4.]
 [-2.  0. -1. -2. -3. -4. -2.]
 [-3. -1. -2.  0. -1. -2. -3.]
 [-4. -2. -3. -1.  1.  0. -1.]
 [-5. -3. -1. -2.  0.  2.  1.]
 [-6. -4. -2. -3. -1.  1.  0.]
 [-7. -5. -3. -4. -2.  0.  2.]]


In [4]:
new_A, new_B, score = nw_nucleotides.Needleman_and_wunsch_algo(A,B, distance_matrix)
print("Score",score)
print("A :", new_A)
print("A :", new_B)

2.0
[[0. 2. 2. 2. 2. 2. 2.]
 [1. 0. 0. 0. 2. 2. 2.]
 [1. 0. 2. 1. 0. 0. 0.]
 [1. 1. 0. 0. 2. 2. 1.]
 [1. 1. 0. 1. 0. 2. 2.]
 [1. 1. 0. 1. 1. 0. 2.]
 [1. 1. 0. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 1. 0.]]
Score 2.0
A : _CATG_AC
A : TC_TGAAC


-------

---

In [5]:
new_A, new_B, score = nw_nucleotides.Needleman_and_wunsch_algo(A,B, distance_matrix)
print("Score",score)
print("A :", new_A)
print("A :", new_B)

2.0
[[0. 2. 2. 2. 2. 2. 2.]
 [1. 0. 0. 0. 2. 2. 2.]
 [1. 0. 2. 1. 0. 0. 0.]
 [1. 1. 0. 0. 2. 2. 1.]
 [1. 1. 0. 1. 0. 2. 2.]
 [1. 1. 0. 1. 1. 0. 2.]
 [1. 1. 0. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 1. 0.]]
Score 2.0
A : _CATG_AC
A : TC_TGAAC


In [6]:
protein_2ABL_sequence = 'MGPSENDPNLFVALYDFVASGDNTLSITKGEKLRVLGYNHNGEWCEAQTKNGQGWVPSNYITPVNSLEKHSWYHGPVSRNAAEYLLSSGINGSFLVRESESSPGQRSISLRYEGRVYHYRINTASDGKLYVSSESRFNTLAELVHHHSTVADGLITTLHYPAP'
protein_1OPK_sequence = 'GAMDPSEALQRPVASDFEPQGLSEAARWNSKENLLAGPSENDPNLFVALYDFVASGDNTLSITKGEKLRVLGYNHNGEWCEAQTKNGQGWVPSNYITPVNSLEKHSWYHGPVSRNAAEYLLSSGINGSFLVRESESSPGQRSISLRYEGRVYHYRINTASDGKLYVSSESRFNTLAELVHHHSTVADGLITTLHYPAPKRNKPTIYGVSPNYDKWEMERTDITMKHKLGGGQYGEVYEGVWKKYSLTVAVKTLKEDTMEVEEFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMTYGNLLDYLRECNRQEVSAVVLLYMATQISSAMEYLEKKNFIHRNLAARNCLVGENHLVKVADFGLSRLMTGDTYTAHAGAKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATYGMSPYPGIDLSQVYELLEKDYRMERPEGCPEKVYELMRACWQWNPSDRPSFAEIHQAFETMFQESSISDEVEKELGKRGT'

In [7]:
file_path = "Distance Matrix/BLOSUM62.txt"
if os.path.exists(file_path):
    print('yes')

yes


In [8]:
file_path = "Distance Matrix/BLOSUM62.txt"
# Read the file
with open(file_path, 'r') as file:
    lines = file.readlines()
    # Create the matrix
    matrix = [line.split() for line in lines if not line.startswith('#')]

    # Display the matrix
    for row in matrix:
        print(row)

['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V', 'B', 'Z', 'X', '*']
['A', '4', '-1', '-2', '-2', '0', '-1', '-1', '0', '-2', '-1', '-1', '-1', '-1', '-2', '-1', '1', '0', '-3', '-2', '0', '-2', '-1', '0', '-4']
['R', '-1', '5', '0', '-2', '-3', '1', '0', '-2', '0', '-3', '-2', '2', '-1', '-3', '-2', '-1', '-1', '-3', '-2', '-3', '-1', '0', '-1', '-4']
['N', '-2', '0', '6', '1', '-3', '0', '0', '0', '1', '-3', '-3', '0', '-2', '-3', '-2', '1', '0', '-4', '-2', '-3', '3', '0', '-1', '-4']
['D', '-2', '-2', '1', '6', '-3', '0', '2', '-1', '-1', '-3', '-4', '-1', '-3', '-3', '-1', '0', '-1', '-4', '-3', '-3', '4', '1', '-1', '-4']
['C', '0', '-3', '-3', '-3', '9', '-3', '-4', '-3', '-3', '-1', '-1', '-3', '-1', '-2', '-3', '-1', '-1', '-2', '-2', '-1', '-3', '-3', '-2', '-4']
['Q', '-1', '1', '0', '0', '-3', '5', '2', '-2', '0', '-3', '-2', '1', '0', '-3', '-1', '0', '-1', '-2', '-1', '-2', '0', '3', '-1', '-4']
['E', '-1', '0', '0', '2'

In [9]:
def matrix_to_dict(matrix):
    distance_dict = {}
    # 2.1. fill the dictionary with values from the matrix
    for i in range(len(distance_matrix)):
        row_letter = matrix[0]
        distance_dict[row_letter] = {}
        for j in range(len(distance_matrix[i])):
            col_letters = matrix[0]
            distance_dict[row_letter][col_letters] = distance_matrix[i][j]

In [ ]:
matrix_to_dict(matrix)

In [ ]:
distance_matrix_BLOSUM62 = []
openning_gap = 11
extension_gap = 11
new_protein_2ABL_sequence, new_B_protein_1OPK_sequence, score = nw_nucleotides.Needleman_and_wunsch_algo(protein_2ABL_sequence, protein_1OPK_sequence, distance_matrix, opening_gap= False)
print("Score",score)
print("A :", new_protein_2ABL_sequence)
print("A :", new_B_protein_1OPK_sequence)

---